# Generated by Django 6.1.1 on 2026-09-23 01:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenFamily",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "revoked_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("logout", "Logout"),
                            ("logout_all", "Logout everywhere"),
                            ("reuse_detected", "Refresh token reuse detected"),
                            ("password_change", "Password changed"),
                            ("expired", "Expired"),
                            ("admin", "Revoked by an administrator"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signet_families",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "token families",
            },
        ),
        migrations.CreateModel(
            name="IssuedToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("digest", models.CharField(db_index=True, max_length=64, unique=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="django_signet.tokenfamily",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="tokenfamily",
            index=models.Index(
                fields=["user", "revoked_at"], name="django_sign_user_id_43c391_idx"
            ),
        ),
    ]
